### PR TITLE
added additional facility fields for admin editing

### PR DESCRIPTION
**Pull request by jrabolli**
just additional fields for admin facility editing.  please review

### CODE REVIEW

**Comment by mocerinoj** [comment]
@jrabolli nice! Can you provide a screenshot of the UI?

**Comment by jrabolli** [comment]
Screen Shot 2019-05-14 at 12 10 02 PM

**Comment by mocerinoj** [comment]
cool, what is lunch closings and closings?

**Comment by jrabolli** [comment]
I honestly have no idea, seems dumb and I expect they won't be used much and removed from the system at some point.  But he specifically said it should be editable right now so I did it.

**Pull request merged**
